cassandra:
  contactPoints: localhost
  keyspaceName: myretail
  port: 9042
management:
  info.git.mode: full
  health.cassandra.enabled: true
  endpoint:
    health:
      show-details: always
redSky:
  uri: http://redsky.target.com/
# TODO: refactor tests and disable
spring:
  main:
    allow-bean-definition-overriding: true
