cassandra:
  contactPoints: localhost
  keyspaceName: myretail
  port: 9142
embeddedCassandra.enabled: true
endpoints:
  docs.path: /docs-actuator
  hypermedia.enabled: true
management:
  info.git.mode: full
  security.enabled: false
redsky:
  uri: http://redsky.target.com/
