sudo: required
language: java
jdk:
- openjdk8
services:
- cassandra
- docker
cache:
  directories:
  - "$HOME/.gradle/wrapper"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/caches/jars-1"
  - "$HOME/.gradle/caches/jars-2"
  - "$HOME/.gradle/caches/jars-3"
  - "$HOME/.gradle/caches/3.4.1"
script: "./gradlew build --info"
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
after_success:
- docker login --username $DOCKER_USER --password $DOCKER_PASS
- export REPO=timrs2998/myretail
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
after_failure: find . -name "*.html" -exec cat {} \;
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
