service: default
runtime: custom
env: flex

manual_scaling:
  instances: 1

env_variables:
  JAVA_OPTS: '-DembeddedCassandra.enabled=true'

health_check:
  enable_health_check: True

handlers:
- url: /.well-known
  static_dir: .well-known

