version: '3.7'
services:

  db:
    image: library/cassandra:3.11.4
    ports:
    - '9042:9042'

  app:
    build: .
    environment:
      CASSANDRA_CONTACTPOINTS: db
      CASSANDRA_PORT: '9042'
    image: timrs2998/myretail
    links:
      - db
    ports:
      - '8080:8080'
    restart: unless-stopped
