apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
  - port: 9042
  selector:
    app: cassandra
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - image: library/cassandra:3.11.4
        name: cassandra
        ports:
        - containerPort: 9042
          name: cassandra
