apiVersion: v1
kind: Service
metadata:
  name: myretail
spec:
  ports:
    - port: 8080
  selector:
    app: myretail
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myretail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myretail
  template:
    metadata:
      labels:
        app: myretail
    spec:
      containers:
      - name: myretail
        env:
        - name: CASSANDRA_CONTACTPOINTS
          value: cassandra
        - name: CASSANDRA_PORT
          value: '9042'
        image: timrs2998/myretail
        ports:
        - containerPort: 8080
