apiVersion: v1
kind: Service
metadata:
  name: myretail
spec:
  ports:
    - port: 9042
  selector:
    app: myretail
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myretail
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myretail
    spec:
      containers:
      - name: myretail
        env:
        - name: CASSANDRA_CONTACTPOINTS
          value: cassandra
        - name: CASSANDRA_PORT
          value: '9042'
        image: timrs2998/myretail
        ports:
        - containerPort: 8080
